CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS users (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), email VARCHAR(255) UNIQUE NOT NULL, password_hash VARCHAR(255) NOT NULL, role VARCHAR(50) CHECK (role IN ('admin','staff','parent','student')) NOT NULL, full_name VARCHAR(255) NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS students (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), student_id VARCHAR(50) UNIQUE NOT NULL, user_id UUID UNIQUE REFERENCES users(id) ON DELETE CASCADE, class_name VARCHAR(100) NOT NULL, date_of_birth DATE, guardian_name VARCHAR(255), created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS staff_profiles (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), user_id UUID UNIQUE NOT NULL REFERENCES users(id) ON DELETE CASCADE, staff_id VARCHAR(50) UNIQUE NOT NULL, job_title VARCHAR(100) NOT NULL DEFAULT 'Teacher', created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS parent_profiles (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), user_id UUID UNIQUE NOT NULL REFERENCES users(id) ON DELETE CASCADE, phone VARCHAR(50), created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS parent_students (parent_id UUID NOT NULL REFERENCES parent_profiles(id) ON DELETE CASCADE, student_id UUID NOT NULL REFERENCES students(id) ON DELETE CASCADE, relationship VARCHAR(50) NOT NULL DEFAULT 'Guardian', PRIMARY KEY (parent_id, student_id));
CREATE TABLE IF NOT EXISTS academic_sessions (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), name VARCHAR(20) UNIQUE NOT NULL, is_current BOOLEAN NOT NULL DEFAULT FALSE, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS academic_terms (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), name VARCHAR(30) UNIQUE NOT NULL, sort_order SMALLINT NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS subjects (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), name VARCHAR(100) UNIQUE NOT NULL, code VARCHAR(30) UNIQUE, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS results (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), student_id VARCHAR(50) NOT NULL REFERENCES students(student_id) ON DELETE CASCADE, session VARCHAR(50) NOT NULL, term VARCHAR(50) NOT NULL, subject VARCHAR(100) NOT NULL, ca_score NUMERIC(5,2) NOT NULL DEFAULT 0.00 CHECK (ca_score >= 0 AND ca_score <= 40), exam_score NUMERIC(5,2) NOT NULL DEFAULT 0.00 CHECK (exam_score >= 0 AND exam_score <= 60), total_score NUMERIC(5,2) GENERATED ALWAYS AS (ca_score + exam_score) STORED, grade VARCHAR(5) NOT NULL, remark TEXT, is_published BOOLEAN NOT NULL DEFAULT FALSE, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE (student_id, session, term, subject));
CREATE TABLE IF NOT EXISTS result_publications (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), session VARCHAR(50) NOT NULL, term VARCHAR(50) NOT NULL, published_by UUID NOT NULL REFERENCES users(id), published_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE (session, term));
CREATE TABLE IF NOT EXISTS result_audit_logs (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), result_id UUID NOT NULL REFERENCES results(id) ON DELETE CASCADE, changed_by UUID NOT NULL REFERENCES users(id), action VARCHAR(30) NOT NULL, old_ca_score NUMERIC(5,2), old_exam_score NUMERIC(5,2), new_ca_score NUMERIC(5,2), new_exam_score NUMERIC(5,2), created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_students_user_id ON students(user_id);
CREATE INDEX IF NOT EXISTS idx_results_student_term ON results(student_id, session, term);
CREATE INDEX IF NOT EXISTS idx_results_published_lookup ON results(student_id, session, term, is_published);
CREATE INDEX IF NOT EXISTS idx_parent_students_student ON parent_students(student_id);
