'use client';

import { FormEvent, useState } from 'react';
import { useRouter } from 'next/navigation';

export default function StudentLogin(){
  const router=useRouter(); const [identifier,setIdentifier]=useState(''); const [password,setPassword]=useState(''); const [error,setError]=useState(''); const [loading,setLoading]=useState(false);
  async function submit(e:FormEvent){e.preventDefault();setLoading(true);setError('');const res=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({identifier,password})});const data=await res.json();if(!res.ok){setError(data.error||'Unable to sign in.');setLoading(false);return;}if(data.role!=='student'){setError('This login is not a student account.');setLoading(false);return;}router.push('/portal/student/dashboard');}
  return <main className="page-shell grid min-h-[70vh] items-center gap-12 py-16 lg:grid-cols-[1fr_.7fr]"><div><p className="eyebrow text-[var(--gold)]">Student portal</p><h1 className="display mt-4 text-6xl leading-none md:text-8xl">Your progress, in one place.</h1><p className="mt-6 max-w-xl leading-7 text-[var(--muted)]">Sign in with your school account to view results that have been officially published.</p></div><form onSubmit={submit} className="rounded-[2rem] border border-[var(--line)] bg-[var(--surface)] p-7 md:p-9"><label className="block"><span className="eyebrow">Email / Student account</span><input value={identifier} onChange={e=>setIdentifier(e.target.value)} required className="mt-2 w-full border-b border-[var(--line)] bg-transparent py-3 outline-none focus:border-[var(--brand)]" /></label><label className="mt-7 block"><span className="eyebrow">Password</span><input type="password" value={password} onChange={e=>setPassword(e.target.value)} required className="mt-2 w-full border-b border-[var(--line)] bg-transparent py-3 outline-none focus:border-[var(--brand)]" /></label>{error&&<p role="alert" className="mt-5 text-sm text-red-700">{error}</p>}<button disabled={loading} className="mt-8 w-full rounded-full bg-[var(--brand)] px-5 py-3 font-bold text-white transition hover:bg-[var(--brand-dark)] disabled:opacity-60">{loading?'Signing in…':'Sign in'}</button></form></main>;
}
